# Generated by Django 5.1.3 on 2024-11-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logros', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrotienda',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tienda'),
        ),
        migrations.AddField(
            model_name='logrousuario',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logros.logro'),
        ),
    ]
