# Generated by Django 5.1.2 on 2024-10-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
