# Generated by Django 5.1.3 on 2024-11-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0003_initial'),
        ('pedidos', '0002_initial'),
        ('productos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioComprador',
            new_name='Comprador',
        ),
        migrations.RenameModel(
            old_name='UsuarioPropietario',
            new_name='Propietario',
        ),
    ]
