# Generated by Django 5.1.3 on 2024-11-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariocomprador_usuariopropietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('username', 'email')},
        ),
    ]
