# Generated by Django 5.1.3 on 2024-11-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='usuarios.usuariopropietario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tienda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.tienda'),
        ),
    ]
