# Generated by Django 5.1.2 on 2024-10-23 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0.99, validators=[django.core.validators.MinValueValidator(0.99)]),
        ),
    ]
