# Generated by Django 5.1.2 on 2024-10-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0003_inventarioproducto_resenna'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocentral',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='categorias.categoria'),
        ),
    ]
